#!/bin/bash
PROGNAME=${0##*/}
fatal() { echo "FATAL: $PROGNAME: $*" >&2; exit 2; }
info() { echo "INFO: $PROGNAME: $*" >&2; }

if [[ -f /var/lib/grafana/grafana.db ]]; then
    ndashboard=$(sqlite3 /var/lib/grafana/grafana.db 'select count(*) from dashboard')
    if [[ $ndashboard -gt 0 && $FORCE != 1 ]]; then
        fatal 'Database not empty, need force to continue'
    fi
fi

if [[ $RESET == 1 ]]; then
    systemctl stop grafana-server
    dpkg -r grafana
    rm -rfv /etc/grafana /var/lib/grafana
    dpkg -i /media/packages/grafana*.deb
fi

ts=$(date +%s)
wait=0

while (( wait++ < 30 )); do
    sz=($(stat -c %s /var/lib/grafana/grafana.db) "${sz[@]}")
    (( $? == 0 && sz[0] == sz[1] && sz[1] == sz[2] )) && { wait=0; break; }
    info "database not ready, try $wait, wait"
    sleep 1
done
(( wait == 0 )) || fatal 'database not ready, timeout'
info 'Stop grafana'
systemctl stop grafana-server

cp -a /var/lib/grafana/grafana.db{,".$ts"}
for sql in ${0%/*}/*-grafana-*.sql; do
    info "Apply ${sql##*/}"
    if ! sqlite3 /var/lib/grafana/grafana.db < "$sql"; then
        cp -a /var/lib/grafana/grafana.db{".$ts",}
        fatal "Update failed, abort"
    fi
done

info 'Update configuration'
cp -a /etc/grafana/grafana.ini{,".$ts"}
awk '
{ comment = 0; key = ""; value = ""; }
match($0, /^\s*\[([^\]]+)\]/, cap) { section = cap[1]; print $0; next; }
match($0, /^\s*(;\s*)?([^[:space:]=]+)[^=]*=\s*(.*)/, cap) { comment = cap[1]?1:0; key = cap[2]; value = cap[3]; }
section == "server" && key == "http_addr" { print key " = 127.0.0.1"; next; }
section == "server" && key == "root_url" { print key " = /grafana"; next; }
section == "auth.anonymous" && key == "enabled" { print key " = true"; next; }
section == "auth.anonymous" && key == "org_role" { print key " = Viewer"; next; }
section == "users" && key == "default_theme" { print key " = light"; next; }
{ print $0; }
' "/etc/grafana/grafana.ini.$ts" > /etc/grafana/grafana.ini

info 'Start grafana'
systemctl start grafana-server
