#!/bin/bash
PROGNAME=${0##*/}
fatal() { echo "FATAL: $PROGNAME: $*" >&2; exit 2; }
info() { echo "INFO: $PROGNAME: $*" >&2; }

source /etc/profile.d/kompot-path.sh ||
    fatal 'Failed to source /etc/profile.d/kompot-path.sh'

if [[ -f /var/lib/grafana/grafana.db ]]; then
    ndashboard=$(sqlite3 /var/lib/grafana/grafana.db 'select count(*) from dashboard')
    if [[ $ndashboard -gt 0 && $FORCE != 1 ]]; then
        fatal 'Database not empty, need force to continue'
    fi
fi

if [[ $RESET == 1 ]]; then
    zservice stop grafana-server
    dpkg -r grafana
    rm -rfv /etc/grafana /var/lib/grafana
    dpkg -i /media/packages/grafana*.deb
fi

ts=$(date +%s)
wait=0

while (( wait++ < 30 )); do
    sz=($(stat -c %s /var/lib/grafana/grafana.db) "${sz[@]}")
    (( $? == 0 && sz[0] == sz[1] && sz[1] == sz[2] )) && { wait=0; break; }
    info "database not ready, try $wait, wait"
    sleep 1
done
(( wait == 0 )) || fatal 'database not ready, timeout'
info 'Stop grafana'
zservice stop grafana-server

cp -a /var/lib/grafana/grafana.db{,".$ts"}
for sql in ${0%/*}/*-grafana-*.sql; do
    info "Apply ${sql##*/}"
    if ! sqlite3 /var/lib/grafana/grafana.db < "$sql"; then
        cp -a /var/lib/grafana/grafana.db{".$ts",}
        fatal "Update failed, abort"
    fi
done

info 'Update configuration'
cp -a /etc/grafana/grafana.ini{,".$ts"}
install -m 640 -g grafana /opt/kompot/share/configs/grafana/grafana.ini /etc/grafana/grafana.ini

info 'Start grafana'
zservice start grafana-server
